import { createClient } from '@supabase/supabase-js'

const DEFAULT_SUPABASE_URL = 'https://yajkfglagnyvenddyvok.supabase.co'

function bearerToken(req) {
  const header = String(req.headers.authorization || '')
  return /^Bearer\s+\S+$/i.test(header)
    ? header.replace(/^Bearer\s+/i, '').trim()
    : ''
}

export async function handleAnalyticsSessionRequest(req, res, { readJson, send, corsHeaders }) {
  if (req.method === 'OPTIONS') {
    return send(res, 204, '', corsHeaders(req))
  }

  if (req.method !== 'POST') {
    return send(res, 405, JSON.stringify({ error: 'Method not allowed' }), {
      'Content-Type': 'application/json; charset=utf-8',
      Allow: 'POST, OPTIONS',
      ...corsHeaders(req),
    })
  }

  const accessToken = bearerToken(req)
  const serviceKey = String(process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim()
  const supabaseUrl = String(
    process.env.SUPABASE_URL ||
    process.env.VITE_SUPABASE_URL ||
    DEFAULT_SUPABASE_URL
  ).trim().replace(/\/+$/, '')

  if (!accessToken) {
    return send(res, 401, JSON.stringify({ error: 'Unauthorized' }), {
      'Content-Type': 'application/json; charset=utf-8',
      ...corsHeaders(req),
    })
  }

  if (!serviceKey) {
    return send(res, 503, JSON.stringify({ error: 'Analytics session linking is not configured.' }), {
      'Content-Type': 'application/json; charset=utf-8',
      ...corsHeaders(req),
    })
  }

  try {
    const body = await readJson(req)
    const sessionId = String(body?.session_id || '').trim()

    // Session IDs are generated by the HJ web client. Keep this endpoint
    // narrow so arbitrary database identifiers cannot be submitted.
    if (!/^hj_[A-Za-z0-9_-]{13,127}$/.test(sessionId)) {
      return send(res, 400, JSON.stringify({ error: 'Invalid analytics session id.' }), {
        'Content-Type': 'application/json; charset=utf-8',
        ...corsHeaders(req),
      })
    }

    const adminClient = createClient(supabaseUrl, serviceKey, {
      auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false },
    })

    const { data: userData, error: userError } = await adminClient.auth.getUser(accessToken)
    const userId = userData?.user?.id
    if (userError || !userId) {
      return send(res, 401, JSON.stringify({ error: 'Invalid or expired login session.' }), {
        'Content-Type': 'application/json; charset=utf-8',
        ...corsHeaders(req),
      })
    }

    const { error } = await adminClient
      .from('analytics_session_links')
      .upsert(
        { session_id: sessionId, user_id: userId },
        { onConflict: 'session_id,user_id', ignoreDuplicates: true }
      )

    if (error) {
      console.warn('[analytics-session-link] database write failed:', String(error.message || error).slice(0, 300))
      return send(res, 500, JSON.stringify({ error: 'Analytics session link failed.' }), {
        'Content-Type': 'application/json; charset=utf-8',
        ...corsHeaders(req),
      })
    }

    return send(res, 200, JSON.stringify({ linked: true }), {
      'Content-Type': 'application/json; charset=utf-8',
      ...corsHeaders(req),
    })
  } catch (error) {
    console.warn('[analytics-session-link] request failed:', String(error?.message || error).slice(0, 300))
    return send(res, 400, JSON.stringify({ error: 'Invalid analytics session link request.' }), {
      'Content-Type': 'application/json; charset=utf-8',
      ...corsHeaders(req),
    })
  }
}
